import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/header/Header'
import SlidableImage from '../components/slidable-image/SlidableImage'
import styles from '../styles/Home.module.css'

import fryGray from '../public/images/fry-gray.jpeg';
import fryColor from '../public/images/fry-color.jpg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header><Header /></header>

      <main className={styles.main}>
	<SlidableImage firstImage={fryGray} secondImage={fryColor} text='Streamowana w FULL HD' />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
